### ISSUE TITLE
Selecting Server World config crashes game

### ISSUE THREAD

**Issue by red2blue** [MrCrayfish/Configured#35] opened 2021-12-11 10:04 UTC
1.18 
v1.5.1

As title mentions, any time I click on the configure option for server configs, my game crashes. I do have existing worlds. 7 actually. I can edit Common and client, but as soon as I click server options, crashes

https://pastebin.com/qjYc0uBK

**Comment by TJT01** [comment] 2021-12-16 04:19
Duplicate of #34

**Closed** 2021-12-16 05:05 UTC
