### ISSUE TITLE
Does not play nice with chance globes, but all other mods I have no issues. Author says go to you instead.

### ISSUE THREAD

**Issue by ExiledMiner04** [MrCrayfish/Configured#20] opened 2021-08-06 14:41 UTC
The game crashed whilst narrating screen
Error: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "p_169401_" is null
Exit Code: -1

This occurs when Trying to edit the config for chance globes with mc crayfish's configured.
Forge is 37.0.25.

**Comment by EwyBoy** [comment] 2021-08-06 19:11
Duplicate of [#17](https://github.com/MrCrayfish/Configured/issues/17)

**Closed** 2021-08-07 02:26 UTC
