### ISSUE TITLE
[1.20.1][Forge] Config files not separated by mod. 

### ISSUE THREAD

**Issue by ffuentesm** [MrCrayfish/Configured#127] opened 2024-02-27 18:59 UTC
Configured: 2.2.2
Catalog: 1.8.0
Forge: 47.1.47

When clicking on a mod config to edit, Configured displays EVERY single config file in the config folder, instead of just that mod config file
![image](https://github.com/MrCrayfish/Configured/assets/44974827/b56e1218-fc22-4a96-9a54-859a2ca324f6)

**Comment by KateReller** [comment] 2024-02-27 19:31
Duplicate of #125, but there has not been a backport of 2.2.3 for 1.20.1 yet.
Version 2.2.0 doesn't have this issue for 1.20.1, so you could downgrade in the meantime.

**Comment by MrCrayfish** [comment] 2024-03-06 22:00
Thanks for the report. Fixed in https://github.com/MrCrayfish/Configured/commit/1c59dacaa26d91a6117d1b2b2c9cf38f257b8393
Patch releasing soon

**Closed as completed by MrCrayfish** 2024-03-06 22:00 UTC
